export const PathUtil = {
    getSourcePath: function () {
        try {
            throw new Error();
        } catch (e) {
            const stackLines = e.stack.split("\n");
            const callerLine = stackLines[stackLines.length - 1] || stackLines[stackLines.length - 2];
            const match = callerLine.match(/(?:at |@)(.*):\d+:\d+/);
            let path = match ? match[1] : "unknown";
            if (typeof helper !== "undefined") {
                path = helper.toRelativePath(path);
            }
            return path;
        }
    }
}

export const Control = {
    KeySwitch0: "Control.KeySwitch0",
    KeySwitch1: "Control.KeySwitch1",
    KeySwitch2: "Control.KeySwitch2",
    KeySwitch3: "Control.KeySwitch3",
    KeySwitch4: "Control.KeySwitch4",
    KeySwitch5: "Control.KeySwitch5",
    KeySwitch6: "Control.KeySwitch6",
    KeySwitch7: "Control.KeySwitch7",
    KeySwitch8: "Control.KeySwitch8",
    KeySwitch9: "Control.KeySwitch9",
    KeySwitch10: "Control.KeySwitch10",
    KeySwitch11: "Control.KeySwitch11",
    KeySwitch12: "Control.KeySwitch12",
    KeySwitch13: "Control.KeySwitch13",
    KeySwitch14: "Control.KeySwitch14",
    KeySwitch15: "Control.KeySwitch15",
    Button0: "Control.Button0",
    Button1: "Control.Button1",
    Joystick: "Control.Joystick",
    Wheel: "Control.Wheel",
    Display: "Control.Display",
    Ranging: "Control.Ranging",
    Main: "Control.Main"
}

export const Device = {
    KeySwitch0: {
        Status: "$KeySwitch0.Status",
        TimerData: "$KeySwitch0.TimerData"
    },
    KeySwitch1: {
        Status: "$KeySwitch1.Status",
        TimerData: "$KeySwitch1.TimerData"
    },
    KeySwitch2: {
        Status: "$KeySwitch2.Status",
        TimerData: "$KeySwitch2.TimerData"
    },
    KeySwitch3: {
        Status: "$KeySwitch3.Status",
        TimerData: "$KeySwitch3.TimerData"
    },
    KeySwitch4: {
        Status: "$KeySwitch4.Status",
        TimerData: "$KeySwitch4.TimerData"
    },
    KeySwitch5: {
        Status: "$KeySwitch5.Status",
        TimerData: "$KeySwitch5.TimerData"
    },
    KeySwitch6: {
        Status: "$KeySwitch6.Status",
        TimerData: "$KeySwitch6.TimerData"
    },
    KeySwitch7: {
        Status: "$KeySwitch7.Status",
        TimerData: "$KeySwitch7.TimerData"
    },
    KeySwitch8: {
        Status: "$KeySwitch8.Status",
        TimerData: "$KeySwitch8.TimerData"
    },
    KeySwitch9: {
        Status: "$KeySwitch9.Status",
        TimerData: "$KeySwitch9.TimerData"
    },
    KeySwitch10: {
        Status: "$KeySwitch10.Status",
        TimerData: "$KeySwitch10.TimerData"
    },
    KeySwitch11: {
        Status: "$KeySwitch11.Status",
        TimerData: "$KeySwitch11.TimerData"
    },
    KeySwitch12: {
        Status: "$KeySwitch12.Status",
        TimerData: "$KeySwitch12.TimerData"
    },
    KeySwitch13: {
        Status: "$KeySwitch13.Status",
        TimerData: "$KeySwitch13.TimerData"
    },
    KeySwitch14: {
        Status: "$KeySwitch14.Status",
        TimerData: "$KeySwitch14.TimerData"
    },
    KeySwitch15: {
        Status: "$KeySwitch15.Status",
        TimerData: "$KeySwitch15.TimerData"
    },
    Button0: {
        Status: "$Button0.Status",
        TimerData: "$Button0.TimerData"
    },
    Button1: {
        Status: "$Button1.Status",
        TimerData: "$Button1.TimerData"
    },
    Joystick: {
        X: "$Joystick.X",
        Y: "$Joystick.Y",
        Z: "$Joystick.Z",
        MX: "$Joystick.MX",
        MY: "$Joystick.MY",
        MZ: "$Joystick.MZ",
        Button: "$Joystick.Button",
        TimerData: "$Joystick.TimerData"
    },
    Wheel: {
        Delta: "$Wheel.Delta",
        TimerData: "$Wheel.TimerData"
    },
    Display: {
        TimerData: "$Display.TimerData"
    },
    Ranging: {
        Status: "$Ranging.Status",
        Distance: "$Ranging.Distance",
        TimerData: "$Ranging.TimerData"
    },
    Main: {
        TimerData: "$Main.TimerData"
    }
}

export const Command = {
    MouseMove:              "MouseMove",
    MouseTrackingStart:     "MouseTrackingStart",
    MouseTrackingStop:      "MouseTrackingStop",
    MouseTrackingRewind:    "MouseTrackingRewind",
    MouseWheel:             "MouseWheel",
    Click:                  "MouseClick",
    DoubleClick:            "MouseDoubleClick",
    TripleClick:            "MouseTripleClick",
    ButtonPress:            "ButtonPress",
    ButtonRelease:          "ButtonRelease",
    KeyPress:               "KeyPress",
    KeyRelease:             "KeyRelease",
    KeyInput:               "KeyInput",
    MapInput:               "MapInput",
    MapCommand:             "MapCommand",
    PageChange:             "PageChange",
    ApplicationChange:      "ApplicationChange",
    Delay:                  "Delay",
    SetTimer:               "SetTimer",
}

export const Button = {
    Left:                   0x01,
    Middle:                 0x02,
    Right:                  0x03,
    Backward:               0x04,
    Forward:                0x05
}

export const Key = {
    A:              0x04,
    B:              0x05,
    C:              0x06,
    D:              0x07,
    E:              0x08,
    F:              0x09,
    G:              0x0a,
    H:              0x0b,
    I:              0x0c,
    J:              0x0d,
    K:              0x0e,
    L:              0x0f,
    M:              0x10,
    N:              0x11,
    O:              0x12,
    P:              0x13,
    Q:              0x14,
    R:              0x15,
    S:              0x16,
    T:              0x17,
    U:              0x18,
    V:              0x19,
    W:              0x1a,
    X:              0x1b,
    Y:              0x1c,
    Z:              0x1d,
    Key1:           0x1e,
    Key2:           0x1f,
    Key3:           0x20,
    Key4:           0x21,
    Key5:           0x22,
    Key6:           0x23,
    Key7:           0x24,
    Key8:           0x25,
    Key9:           0x26,
    Key0:           0x27,

    Enter:          0x28,
    Return:         0x28,
    Esc:            0x29,
    Backspace:      0x2a,
    Tab:            0x2b,
    Space:          0x2c,
    Minus:          0x2d,
    Equal:          0x2e,
    LeftBrace:      0x2f,
    RightBrace:     0x30,
    Backslash:      0x31,
    HashTilde:      0x32,
    Semicolon:      0x33,
    Apostrophe:     0x34,
    Grave:          0x35,
    Comma:          0x36,
    Dot:            0x37,
    Slash:          0x38,
    CapsLock:       0x39,

    F1:             0x3a,
    F2:             0x3b,
    F3:             0x3c,
    F4:             0x3d,
    F5:             0x3e,
    F6:             0x3f,
    F7:             0x40,
    F8:             0x41,
    F9:             0x42,
    F10:            0x43,
    F11:            0x44,
    F12:            0x45,

    SysReq:         0x46,
    PrintScreen:    0x46,
    ScrollLock:     0x47,
    Pause:          0x48,
    Insert:         0x49,
    Home:           0x4a,
    PageUp:         0x4b,
    Delete:         0x4c,
    End:            0x4d,
    PageDown:       0x4e,
    RightArrow:     0x4f,
    LeftArrow:      0x50,
    DownArrow:      0x51,
    UpArrow:        0x52,

    NumLock:        0x53,
    NumpadDev:      0x54,
    NumpadMul:      0x55,
    NumpadMinus:    0x56,
    NumpadPlus:     0x57,
    NumpadEnter:    0x58,
    Numpad1:        0x59,
    Numpad2:        0x5a,
    Numpad3:        0x5b,
    Numpad4:        0x5c,
    Numpad5:        0x5d,
    Numpad6:        0x5e,
    Numpad7:        0x5f,
    Numpad8:        0x60,
    Numpad9:        0x61,
    Numpad0:        0x62,
    NumpadDot:      0x63,
    ND102:          0x64,
    Compose:        0x65,
    Power:          0x66,
    NumpadEqual:    0x67,

    F13:            0x68,
    F14:            0x69,
    F15:            0x6a,
    F16:            0x6b,
    F17:            0x6c,
    F18:            0x6d,
    F19:            0x6e,
    F20:            0x6f,
    F21:            0x70,
    F22:            0x71,
    F23:            0x72,
    F24:            0x73,

    Open:           0x74,
    Help:           0x75,
    Menu:           0x76,
    Select:         0x77,
    Stop:           0x78,
    Again:          0x79,
    Undo:           0x7a,
    Cut:            0x7b,
    Copy:           0x7c,
    Paste:          0x7d,
    Find:           0x7e,
    Mute:           0x7f,
    VolumeUp:       0x80,
    VolumeDown:     0x81,
    _CapsLock:      0x82,
    _NumLock:       0x83,
    _ScrollLock:    0x84,
    NumpadComma:    0x85,
    _NumpadEqual:   0x86,

    INT_1:          0x87,
    JP_RO:          0x87,
    INT_2:          0x88,
    JP_KANA:        0x88,
    INT_3:          0x89,
    JP_YEN:         0x89,
    INT_4:          0x8a,
    JP_CONVERT:     0x8a,
    INT_5:          0x8b,
    JP_NON_CONVERT: 0x8b,
    INT_6:          0x8c,
    JP_COMMA:       0x8c,
    INT_7:          0x8d,
    INT_8:          0x8e,
    INT_9:          0x8f,

    LANG1:          0x90,
    HANGUL:         0x90,
    LANG2:          0x91,
    HANJA:          0x91,
    LANG3:          0x92,
    KATAKANA:       0x92,
    LANG4:          0x93,
    HIRAGANA:       0x93,
    LANG5:          0x94,
    ZENKAKU_HANKAKU:0x94,
    LANG6:          0x95,
    LANG7:          0x96,
    LANG8:          0x97,
    LANG9:          0x98,

    /* modifier buttons */
    LeftCtrl:       0xe0,
    LeftShift:      0xe1,
    LeftAlt:        0xe2,
    LeftMeta:       0xe3,
    Ctrl:           0xe0,
    Shift:          0xe1,
    Alt:            0xe2,
    Meta:           0xe3,
    RightCtrl:      0xe4,
    RightShift:     0xe5,
    RightAlt:       0xe6,
    RightMeta:      0xe7,
    /*
        The following keys are only available on keyboard devices for Media
     */
    MediaPause:       0xe8,
    MediaStopCd:      0xe9,
    MediaPrevious:    0xea,
    MediaNext:        0xeb,
    MediaEjectCd:     0xec,
    MediaVolumeUp:    0xed,
    MediaVolumeDown:  0xee,
    MediaMute:        0xef,
    MediaWww:         0xf0,
    MediaBack:        0xf1,
    MediaForward:     0xf2,
    MediaStop:        0xf3,
    MediaFind:        0xf4,
    MediaScrollUp:    0xf5,
    MediaScrollDown:  0xf6,
    MediaEdit:        0xf7,
    MediaSleep:       0xf8,
    MediaCoffee:      0xf9,
    MediaRefresh:     0xfa,
    MediaCalc:        0xfb
}

export const PixelFormat = {
    Rgb888: "Rgb888",
    Rgb565: "Rgb565",
    BW1: "BW1"
}

export const Color = {
    RGB: function (r, g, b) {
        return ((r & 0xff) << 16) | ((g & 0xff) << 8) | (b & 0xff);
    },
    Pink:           0xffc0cb,
    LightPink:      0xffb6c1,
    HotPink:        0xff69b4,
    DeepPink:       0xff1493,
    PaleVioletRed:  0xdb7093,
    MediumVioletRed: 0xc71585,
    LightSalmon:    0xffa07a,
    Salmon:         0xfa8072,
    DarkSalmon:     0xe9967a,
    LightCoral:     0xf08080,
    IndianRed:      0xcd5c5c,
    Crimson:        0xdc143c,
    Firebrick:      0xb22222,
    DarkRed:        0x8b0000,
    Red:            0xff0000,
    OrangeRed:      0xff4500,
    Tomato:         0xff6347,
    Coral:          0xff7f50,
    DarkOrange:     0xff8c00,
    Orange:         0xffa500,
    Yellow:         0xffff00,
    LightYellow:    0xffffe0,
    LemonChiffon:   0xfffacd,
    LightGoldenrodYellow : 0xfafad2,
    PapayaWhip:     0xffefd5,
    Moccasin:       0xffe4b5,
    PeachPuff:      0xffdab9,
    PaleGoldenrod:  0xeee8aa,
    Khaki:          0xf0e68c,
    DarkKhaki:      0xbdb76b,
    Gold:           0xffd700,
    Cornsilk:       0xfff8dc,
    BlanchedAlmond: 0xffebcd,
    Bisque:         0xffe4c4,
    NavajoWhite:    0xffdead,
    Wheat:          0xf5deb3,
    Burlywood:      0xdeb887,
    Tan:            0xd2b48c,
    RosyBrown:      0xbc8f8f,
    SandyBrown:     0xf4a460,
    Goldenrod:      0xdaa520,
    DarkGoldenrod:  0xb8860b,
    Peru:           0xcd853f,
    Chocolate:      0xd2691e,
    SaddleBrown:    0x8b4513,
    Sienna:         0xa0522d,
    Brown:          0xa52a2a,
    Maroon:         0x800000,
    DarkOliveGreen: 0x556b2f,
    Olive:          0x808000,
    OliveDrab:      0x6b8e23,
    YellowGreen:    0x9acd32,
    LimeGreen:      0x32cd32,
    Lime:           0x00ff00,
    LawnGreen:      0x7cfc00,
    Chartreuse:     0x7fff00,
    GreenYellow:    0xadff2f,
    SpringGreen:    0x00ff7f,
    MediumSpringGreen : 0x00fa9a,
    LightGreen:     0x90ee90,
    PaleGreen:      0x98fb98,
    DarkSeaGreen:   0x8fbc8f,
    MediumAquamarine: 0x66cdaa,
    MediumSeaGreen: 0x3cb371,
    SeaGreen:       0x2e8b57,
    ForestGreen:    0x228b22,
    Green:          0x008000,
    DarkGreen:      0x006400,
    Aqua:           0x00ffff,
    Cyan:           0x00ffff,
    LightCyan:      0xe0ffff,
    PaleTurquoise:  0xafeeee,
    Aquamarine:     0x7fffd4,
    Turquoise:      0x40e0d0,
    MediumTurquoise: 0x48D1CC,
    DarkTurquoise:  0x00ced1,
    LightSeaGreen:  0x20b2aa,
    CadetBlue:      0x5f9ea0,
    DarkCyan:       0x008b8b,
    Teal:           0x008080,
    LightSteelBlue: 0xb0c4de,
    PowderBlue:     0xb0e0e6,
    LightBlue:      0xadd8e6,
    SkyBlue:        0x87ceeb,
    LightSkyBlue:   0x87cefa,
    DeepSkyBlue:    0x00bfff,
    DodgerBlue:     0x1e90ff,
    CornflowerBlue: 0x6495ed,
    SteelBlue:      0x4682b4,
    RoyalBlue:      0x4169e1,
    Blue:           0x0000ff,
    MediumBlue:     0x0000cd,
    DarkBlue:       0x00008b,
    Navy:           0x000080,
    MidnightBlue:   0x191970,
    Lavender:       0xe6e6fa,
    Thistle:        0xd8bfd8,
    Plum:           0xdda0dd,
    Violet:         0xee82ee,
    Orchid:         0xda70d6,
    Fuchsia:        0xff00ff,
    Magenta:        0xff00ff,
    MediumOrchid:   0xba55d3,
    MediumPurple:   0x9370db,
    BlueViolet:     0x8a2be2,
    DarkViolet:     0x9400d3,
    DarkOrchid:     0x9932cc,
    DarkMagenta:    0x8b008b,
    Purple:         0x800080,
    Indigo:         0x4b0082,
    DarkSlateBlue:  0x483d8b,
    SlateBlue:      0x6a5acd,
    MediumSlateBlue : 0x7b68ee,
    White:          0xffffff,
    Snow:           0xfffafa,
    Honeydew:       0xf0fff0,
    MintCream:      0xf5fffa,
    Azure:          0xf0ffff,
    AliceBlue:      0xf0f8ff,
    GhostWhite:     0xf8f8ff,
    WhiteSmoke:     0xf5f5f5,
    Seashell:       0xfff5ee,
    Beige:          0xf5f5dc,
    OldLace:        0xfdf5e6,
    FloralWhite:    0xfffaf0,
    Ivory:          0xfffff0,
    AntiqueWhite:   0xfaebd7,
    Linen:          0xfaf0e6,
    LavenderBlush:  0xfff0f5,
    MistyRose:      0xffe4e1,
    Gainsboro:      0xdcdcdc,
    LightGray:      0xd3d3d3,
    Silver:         0xc0c0c0,
    DarkGray:       0xa9a9a9,
    Gray:           0x808080,
    DimGray:        0x696969,
    LightSlateGray: 0x778899,
    SlateGray:      0x708090,
    DarkSlateGray:  0x2f4f4f,
    Black:          0x000000
}
